//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KurobaChan.Translations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMsgs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMsgs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KurobaChan.Translations.GlobalMsgs", typeof(GlobalMsgs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用法: KurobaChan [选项]
        ///
        ///可选选项:
        ///--service   以服务模式(静默模式)启动
        ///--show      显示正在运行的KurobaChan实例的主窗口(若启用了&quot;增强安全模式&quot;，则该选项将不起作用)
        ///--help      显示帮助信息.
        /// </summary>
        internal static string CmdArgUsage {
            get {
                return ResourceManager.GetString("CmdArgUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KurobaChan 命令行参数说明.
        /// </summary>
        internal static string CmdArgUsage_Title {
            get {
                return ResourceManager.GetString("CmdArgUsage.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未知的命令行参数: {argument}.
        /// </summary>
        internal static string CmdArgUsage_UnknownArgPrefix {
            get {
                return ResourceManager.GetString("CmdArgUsage.UnknownArgPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求的操作需要提升后的权限。
        ///请尝试使用管理员权限运行KurobaChan。.
        /// </summary>
        internal static string StartError_Permission_UAC {
            get {
                return ResourceManager.GetString("StartError.Permission.UAC", resourceCulture);
            }
        }
        
        internal static string FirstStart_UserAgreement {
            get {
                return ResourceManager.GetString("FirstStart.UserAgreement", resourceCulture);
            }
        }
    }
}
